-- Step 1: Insert into shares_users
INSERT INTO shares_users (share_id, obj_id)
SELECT shares.id, users.id
FROM shares
JOIN users ON shares.email = users.email;


-- NOTE: these will actually be generated by next migration. To do it here would create a misalignment of the
-- column types expected by Drizzle and its journal system.
-- Step 2: Drop column shares.email
-- ALTER TABLE shares DROP COLUMN email;

-- Step 3: Rename column shares.email_visible to shares.email
-- ALTER TABLE shares RENAME COLUMN email_visible TO email;